import type { NpcPlan, NpcPlanStep } from '../npcTypes';
import { SLM_TOKENS, type DynamicEntityMapping } from './SlmVocabulary';

export type SlmDecodeResult =
  | { kind: 'success'; plans: NpcPlan[] }
  | { kind: 'escalate'; reason: string };

export class SlmOutputAdapter {
  /**
   * Decodes an integer token sequence generated by the SLM into valid NpcPlan[] DSL.
   * Automatically triggers an escalation if the sequence contains ESCALATE or is malformed.
   */
  static decode(
    outputTokens: Int32Array | number[],
    mapping: DynamicEntityMapping,
    npcId: string
  ): SlmDecodeResult {
    const steps: NpcPlanStep[] = [];
    const tokens = Array.from(outputTokens);

    let i = 0;
    while (i < tokens.length) {
      const token = tokens[i];
      i++;

      if (token === SLM_TOKENS.PAD || token === SLM_TOKENS.START) continue;
      if (token === SLM_TOKENS.END) break;

      if (token === SLM_TOKENS.ESCALATE) {
        return { kind: 'escalate', reason: 'Model explicitly requested escalation' };
      }

      // Helper to resolve an entity ID from the next token
      const nextEntityId = (): string | null => {
        if (i >= tokens.length) return null;
        const targetToken = tokens[i++];
        return mapping.indexToId.get(targetToken) || null;
      };

      switch (token) {
        case SLM_TOKENS.MOVE_TO: {
          const targetId = nextEntityId();
          if (!targetId) return { kind: 'escalate', reason: 'MOVE_TO missing valid targetId' };
          steps.push({ type: 'MOVE_TO', targetId });
          break;
        }
        case SLM_TOKENS.TAKE: {
          const targetId = nextEntityId();
          if (!targetId) return { kind: 'escalate', reason: 'TAKE missing valid targetId' };
          steps.push({ type: 'TAKE', targetId });
          break;
        }
        case SLM_TOKENS.OPEN: {
          const targetId = nextEntityId();
          if (!targetId) return { kind: 'escalate', reason: 'OPEN missing valid targetId' };
          steps.push({ type: 'OPEN', targetId });
          break;
        }
        case SLM_TOKENS.CLOSE: {
          const targetId = nextEntityId();
          if (!targetId) return { kind: 'escalate', reason: 'CLOSE missing valid targetId' };
          steps.push({ type: 'CLOSE', targetId });
          break;
        }
        case SLM_TOKENS.LOOK: {
          const targetId = nextEntityId();
          if (!targetId) return { kind: 'escalate', reason: 'LOOK missing valid targetId' };
          steps.push({ type: 'LOOK', targetId });
          break;
        }
        case SLM_TOKENS.EXAMINE: {
          const targetId = nextEntityId();
          if (!targetId) return { kind: 'escalate', reason: 'EXAMINE missing valid targetId' };
          steps.push({ type: 'EXAMINE', targetId });
          break;
        }
        case SLM_TOKENS.TRAVERSE_EXIT: {
          const targetId = nextEntityId();
          if (!targetId)
            return { kind: 'escalate', reason: 'TRAVERSE_EXIT missing valid targetId' };
          steps.push({ type: 'TRAVERSE_EXIT', targetId });
          break;
        }
        case SLM_TOKENS.USE: {
          const itemId = nextEntityId();
          const targetId = nextEntityId();
          if (!itemId || !targetId) {
            return { kind: 'escalate', reason: 'USE missing valid itemId or targetId' };
          }
          steps.push({ type: 'USE', itemId, targetId });
          break;
        }
        case SLM_TOKENS.PUT: {
          const itemId = nextEntityId();
          const targetId = nextEntityId();
          if (!itemId) return { kind: 'escalate', reason: 'PUT missing valid itemId' };
          steps.push({ type: 'PUT', itemId, targetId });
          break;
        }
        case SLM_TOKENS.WAIT: {
          steps.push({ type: 'WAIT', ms: 1000 });
          break;
        }
        default: {
          // If we encounter an unexpected token or unhandled action, escalate
          return { kind: 'escalate', reason: `Unknown or unhandled token: ${token}` };
        }
      }
    }

    if (steps.length === 0) {
      return { kind: 'escalate', reason: 'Decoded plan produced 0 steps' };
    }

    const plan: NpcPlan = {
      npcId,
      steps,
    };

    return { kind: 'success', plans: [plan] };
  }
}
